DROP DATABASE IF EXISTS rawati;

CREATE DATABASE IF NOT EXISTS rawati;

USE rawati;

CREATE TABLE users (
    user_id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL
);
