DROP DATABASE IF EXISTS mars;

CREATE DATABASE IF NOT EXISTS mars;

USE mars;

CREATE TABLE users (
    user_id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL
);
