version: "3.9"
services:
  db:
    image: mysql:8-debian
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
       MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./scripts/sql:/docker-entrypoint-initdb.d:ro

  docs:
    image: swaggerapi/swagger-ui:v4.11.1
    ports:
      - "8081:8080"
    environment:
      - SWAGGER_JSON=/foo/swagger.json
      - BASE_URL=/swagger
    volumes:
      - ./docs:/foo
