version: "3.9"
services:
  db:
    image: mysql:8-debian
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
       MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
