name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Prepare test
      run: make test-prepare

    - name: Test
      run: |
        sleep 10
        make test-start

    - name: Clean test
      if: always()
      run: make test-clean

  deploy-docs:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Generate docs
      run: |
        go install github.com/swaggo/swag/cmd/swag@latest && go mod download
        make docs-gen

    - name: Deploy to heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "rawatidocs"
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        appdir: "docs"
        usedocker: true
