name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Prepare test
      run: make test-prepare

    - name: Test
      run: make test-start

    - name: Clean test
      if: always()
      run: make test-clean
