name: Test Deploy to Cloud Run

on:
  push:
    branches: [ deploy-test ]

env:
  service: rawati-backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - id: auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v0
      with:
        service: ${{ env.service }}
        image: gcr.io/${{ secrets.GCP_PROJECT }}/${{ env.service }}:${{ GITHUB_SHA }}
        region: asia-southeast1
        env_vars: |
          INSTANCE_CONNECTION_NAME=${{ secrets.INSTANCE_CONNECTION_NAME }},
          DB_USER=${{ secrets.DB_USER }},
          DB_PASS=${{ secrets.DB_PASS }},
          DB_NAME=${{ secrets.DB_NAME }}
        flags: --timeout=300 --min-instances=0 --max-instances=1 --port=8080 --set-cloudsql-instances=${{ secrets.SQL_INSTANCE }}

